### ISSUE TITLE
'[String]' does not have member name 'indexOf'

### ISSUE THREAD

**Issue by ban9ban3** [Vaberer/Google-Material-Design-Icons-Swift#1]
Can you fix this?

**Comment by Vaberer** [comment]
Hello, A library is adjusted to Swift 2 but I created a branch for swift 1.2

If you use pods, use
```pod 'Google-Material-Design-Icons-Swift', :git => 'https://github.com/Vaberer/Google-Material-Design-Icons-Swift.git', :branch => 'swift1.2'```
