### ISSUE TITLE
iOS 8 support

### ISSUE THREAD

**Issue by teristam** [Vaberer/Google-Material-Design-Icons-Swift#2]
Hi, I am trying to use material design icon but encountered the following error:

Unable to satisfy the following requirements

I check the pod record at [cocoapod](https://github.com/CocoaPods/Specs/blob/master/Specs/Google-Material-Design-Icons-Swift/1.0.0/Google-Material-Design-Icons-Swift.podspec.json) it seems that this  require iOS 9 to work. Is there any plan to support iOS 8? Thank you!

**Comment by Vaberer** [comment]
Hello, thanks for writing this issue. Now, it's fixed. change pod version to 
```pod 'Google-Material-Design-Icons-Swift', '~> 1.0.1'```
